export const operatingModesFallback = ['Doorstep Scrap Pickup', 'Business Bulk Clearance'];

export const locationFallback = [
  { _id: 'loc-575001', pinCode: '575001', areaName: 'Mangalore Central', city: 'Mangaluru', state: 'Karnataka' },
  { _id: 'loc-575007', pinCode: '575007', areaName: 'Adyar', city: 'Mangaluru', state: 'Karnataka' },
  { _id: 'loc-575011', pinCode: '575011', areaName: 'Baikampady', city: 'Mangaluru', state: 'Karnataka' },
  { _id: 'loc-575013', pinCode: '575013', areaName: 'Kulur', city: 'Mangaluru', state: 'Karnataka' },
  { _id: 'loc-575014', pinCode: '575014', areaName: 'Surathkal', city: 'Mangaluru', state: 'Karnataka' },
  { _id: 'loc-575019', pinCode: '575019', areaName: 'Kulai', city: 'Mangaluru', state: 'Karnataka' },
  { _id: 'loc-576201', pinCode: '576201', areaName: 'Kundapura', city: 'Kundapura', state: 'Karnataka' },
  { _id: 'loc-576214', pinCode: '576214', areaName: 'Byndoor', city: 'Byndoor', state: 'Karnataka' },
  { _id: 'loc-576233', pinCode: '576233', areaName: 'Jadkal', city: 'Kundapura', state: 'Karnataka' },
];

export const scrapCategoryFallback = [
  {
    _id: 'scrap-iron',
    name: 'Iron & Steel Scrap',
    description: 'Heavy metal scrap, grills, utensils, rods, and steel leftovers.',
    basePrice: 28,
    imageUrl: '/scrap/metal-scrap-yard.jpeg',
  },
  {
    _id: 'scrap-copper',
    name: 'Copper Wire Scrap',
    description: 'Copper wire coils, motor copper, cable leftovers, and copper-rich scrap.',
    basePrice: 560,
    imageUrl: '/scrap/copper-wire-spool.jpeg',
  },
  {
    _id: 'scrap-aluminium',
    name: 'Aluminium Scrap',
    description: 'Aluminium sections, vessels, profiles, and lightweight fabrication scrap.',
    basePrice: 120,
    imageUrl: '/scrap/aluminum-rolls-factory.svg',
  },
  {
    _id: 'scrap-mixed-metal',
    name: 'Mixed Metal Scrap',
    description: 'Mixed metal parts, fittings, hardware, and assorted recyclable metal items.',
    basePrice: 40,
    imageUrl: '/scrap/metal-scrap-yard.jpeg',
  },
  {
    _id: 'scrap-paper',
    name: 'Paper & Cardboard',
    description: 'Newspaper bundles, cartons, and mixed paper recyclables.',
    basePrice: 14,
    imageUrl: '/scrap/paper-scrap-stack.jpeg',
  },
  {
    _id: 'scrap-plastic',
    name: 'Plastic & Household Mix',
    description: 'Dry household recyclables, bottles, containers, and packaging.',
    basePrice: 18,
    imageUrl: '/scrap/plastic-scrap-mix.webp',
  },
  {
    _id: 'scrap-ewaste',
    name: 'E-Waste Devices',
    description: 'Phones, chargers, wires, laptops, and small electronic items.',
    basePrice: 42,
    imageUrl: '/scrap/mobile-scrap-phones.avif',
  },
];

export const serviceFallback = [
  {
    _id: 'service-doorstep',
    name: 'Doorstep Scrap Pickup',
    serviceGroup: 'service',
    description: 'Scheduled home pickup for recyclable scrap across the service area.',
    basePrice: 99,
    imageUrl: '/services/doorstep-scrap-pickup.webp',
  },
  {
    _id: 'service-business',
    name: 'Business Bulk Clearance',
    serviceGroup: 'service',
    description: 'Commercial pickup for warehouses, schools, shops, and offices.',
    basePrice: 499,
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=80',
  },
  {
    _id: 'service-indoor-home-cleaning',
    name: 'Indoor Full Home Cleaning',
    serviceGroup: 'homeService',
    description: 'Full indoor house cleaning covering rooms, hall, kitchen, and bathroom areas.',
    basePrice: 2499,
    imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80',
  },
  {
    _id: 'service-home-deep-cleaning',
    name: 'Home Deep Cleaning Service',
    serviceGroup: 'homeService',
    description: 'Detailed deep-cleaning package for the full house with surface and corner treatment.',
    basePrice: 3299,
    imageUrl: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=900&q=80',
  },
  {
    _id: 'service-outdoor-cleaning',
    name: 'Outdoor Cleaning Service',
    serviceGroup: 'homeService',
    description: 'Outdoor cleaning for terrace, balcony, yard, parking, and compound spaces.',
    basePrice: 1899,
    imageUrl: '/services/outdoor-cleaning-service.webp',
  },
  {
    _id: 'service-water-tank-cleaning',
    name: 'Water Tank Cleaning',
    serviceGroup: 'homeService',
    description: 'Tank wash, sludge removal, and cleaning service for overhead and underground tanks.',
    basePrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=80',
  },
  {
    _id: 'service-bathroom-cleaning',
    name: 'Bathroom Deep Cleaning',
    serviceGroup: 'homeService',
    description: 'Bathroom cleaning for tiles, wash basins, fittings, mirrors, and stain removal.',
    basePrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=900&q=80',
  },
  {
    _id: 'service-kitchen-cleaning',
    name: 'Kitchen Deep Cleaning',
    serviceGroup: 'homeService',
    description: 'Kitchen cleaning for counters, cabinets, sink area, and grease-prone surfaces.',
    basePrice: 1299,
    imageUrl: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80',
  },
  {
    _id: 'service-plumbing',
    name: 'Plumbing Work',
    serviceGroup: 'homeService',
    description: 'Plumbing support for leakage, taps, sinks, drainage issues, and fittings.',
    basePrice: 499,
    imageUrl: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=900&q=80',
  },
  {
    _id: 'service-electrical',
    name: 'Electrical Work',
    serviceGroup: 'homeService',
    description: 'Electrical support for switches, fans, lights, basic wiring, and fixture changes.',
    basePrice: 599,
    imageUrl: 'https://images.unsplash.com/photo-1713937400833-f817938b51e4?auto=format&fit=crop&fm=jpg&q=80&w=1600',
  },
  {
    _id: 'service-labour-supply',
    name: 'Labour Supply',
    serviceGroup: 'homeService',
    description: 'General labour service for moving, loading, unloading, and site support tasks.',
    basePrice: 899,
    imageUrl: '/services/labour-supply.jpeg',
  },
  {
    _id: 'service-sofa-carpet',
    name: 'Sofa & Carpet Cleaning',
    serviceGroup: 'homeService',
    description: 'Soft furnishing cleaning for sofas, carpets, cushions, and upholstery surfaces.',
    basePrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80',
  },
  {
    _id: 'service-ewaste',
    name: 'E-Waste Pickup Drive',
    serviceGroup: 'service',
    description: 'Safe electronics collection for homes, apartments, and institutions.',
    basePrice: 149,
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80',
  },
  {
    _id: 'service-factory',
    name: 'Factory Scrap Segregation',
    serviceGroup: 'service',
    description: 'On-site sorting and dispatch support for industrial scrap loads.',
    basePrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=900&q=80',
  },
];
